### ISSUE TITLE
Problem with long jobs containing identities

### ISSUE THREAD

**Issue by fbm2718** [Qiskit/qiskit-tutorials#382] opened 2018-11-15 19:46 UTC
## Description
Hi guys,
I recently encountered quite a strange problem. 

I create some simple quantum circuits for all five qubits in ibmqx4. The circuits are as follows - for each qubit there are four circuits. Every second is an identity, and every other second is a random unitary. This way I create 20 circuits, from which every second is an identity. 

Here are exemplary results: https://image.ibb.co/i1uSS0/wrong-results-identity.png
(apologies for a stopgap with this picture).
(You can also checkout this job via ID:  5bedc5e90c1cc100588702f4)

If you look closely, for qubit 0 it is okay and for qubit 3 it is okay. For rest of the qubits the numbers appear to have no sense. 

I am pretty sure that my circuits are okay, I create them in the loop and have printed qasm of every circuit to check out if there were no mistakes. 

My guess is that there's something wrong on the software level rather than hardware, since if I run those circuits in separate jobs - i.e. for each qubit 4 circuits, but separately, then it is okay.

Could you somehow take a look if this can be fixed?

Best regards,
Filip 

## Environment
* QISKit version: 0.6.0
* Python version: 3.6.5

**Comment by quantumjim** [comment] 2019-03-20 15:17
Unclear what the issue is, and it seems to be a Terra issue anyway, so closing.

**Closed by quantumjim** 2019-03-20 15:17 UTC
Labels: bug
