### ISSUE TITLE
6_examples_max_cut_and_tsp.ipynb sphinx math expression not rendered

### ISSUE THREAD

**Issue by ivanightingale** [Qiskit/qiskit-tutorials#978] opened 2020-08-04 15:29 UTC
## Description
A math expression in 6_examples_max_cut_and_tsp.ipynb is not rendered properly on the webpage:
![image](https://user-images.githubusercontent.com/31260816/89312607-760ef280-d645-11ea-921d-ee80cdaa7cc3.png)

#### Browsers used
Microsoft Edge, Google Chrome

#### Operating systems used
Windows 10, Ubuntu 20.04 LTS

**Comment by tgag17** [comment] 2020-09-21 08:19
Hi! Can I work on this?

**Comment by divshacker** [comment] 2021-03-27 04:57
Hey @ivanightingale now I can't see this problem on website. Maybe someone have fixed this issue already. If the problem is resolved according to you then please close this issue. 
Thank You

**Comment by divshacker** [comment] 2021-03-29 07:23
@nonhermitian  I think You can close this issue

**Closed** 2021-08-05 19:33 UTC
Labels: documentation
