### ISSUE TITLE
Duplicated circuit visualizations on Quantum Lab

### ISSUE THREAD

**Issue by filippotramonto** [Qiskit/qiskit-tutorials#1180] opened 2021-05-11 20:44 UTC
### Informations

- **Qiskit version**: qiskit version present on Quantum Lab
- **Python version**: Python version on Quantum Llab
- **Operating system**: OS on Quantum Lab

### What is the current behavior?
In all tutorials where the command `%matplotlib inline` in executed, when then the command `.draw('mpl')` is executed for visualize the circuit the circuit is drawn 2 times. 

### Steps to reproduce the problem
- run a cell containing `%matplotlib inline`
- run a cell containing `.draw('mpl')` 

### What is the expected behavior?
The circuit should be drawn only one time

### Suggested solutions
Remove the line with `%matplotlib inline`

**Comment by clausia** [comment] 2021-07-13 07:39
Duplicate of #1201

**Comment by zohimchandani** [comment] 2021-08-10 11:54
I dont have `%matplotlib inline` explicitly defined in my notebook but `circuit.draw('mpl')` produces 2 outputs. Any ideas whats happening there?

**Comment by divshacker** [comment] 2021-08-10 12:05
> I dont have `%matplotlib inline` explicitly defined in my notebook but `circuit.draw('mpl')` produces 2 outputs. Any ideas whats happening there?

Hey you can look in Qiskit/qiskit-terra#6889.
Hope this helps 🙂

**Closed** 2023-08-18 20:47 UTC
Labels: bug
