### ISSUE TITLE
Directory restructure from `stable/0.15.x` to `master` breaks IQX UI

### ISSUE THREAD

**Issue by mriedem** [Qiskit/qiskit-tutorials#929] opened 2020-06-30 15:31 UTC
### Informations

- **Qiskit version**: 0.19.6 (IQX Jupyter notebook site)
- **Python version**: n/a
- **Operating system**: n/a

### What is the current behavior?

The IQX jupyter notebooks page shows the tutorials based on the `qiskit-tutorials/qiskit` path which comes from the `stable/0.15.x` branch structure:

https://github.com/Qiskit/qiskit-tutorials/tree/stable/0.15.x/qiskit

![image](https://user-images.githubusercontent.com/3237936/86145036-0f357100-babc-11ea-8526-9f6e6185a865.png)

With the `master` branch changes to restructure the directories, that `qiskit` subdirectory no longer exists and the paths have changed, e.g. `qiskit/1_start_here.ipynb` from `stable/0.15.x` is now `start_here.ipynb` from the root of the repo on the `master` branch. The `advanced` and `fundamentals` directories are also gone. I realize this was an intentional restructure but it prevents a smooth transition from the tutorials `stable/0.15.x` branch to the `master` or `stable/0.19.x` branch for the IQX jupyter notebooks UI.

### Steps to reproduce the problem

Internally we upgraded to the `master` branch of the tutorials and found that the paths in the IQX UI were broken.

### What is the expected behavior?

The IQX jupyter notebooks UI should continue to work regardless of the change in directory structure in the tutorials repo.

### Suggested solutions

The simplest solution to continue to start from a `start here` notebook would be to just create a `qiskit/` symbolic link in the tutorials repo back to the root of the project where the renamed `start_here.ipynb` file exists.

Note that this wouldn't fix the loss of the `advanced` and `fundamentals` directories but that's probably less of a concern, the bigger issue is getting to the correct `start here` notebook which then links to the other notebooks (including being able to get to the legacy notebooks which may or may not work with qiskit>=0.19.0).

**Comment by mriedem** [comment] 2020-06-30 15:41
It might also be worth creating a symlink from `qiskit/advanced` to `legacy_tutorials` since that's where those notebooks seem to have gone now but I'm not sure. Similarly, `qiskit/fundamentals` could link to `tutorials` since that's where that content seems to have moved.

**Comment by nonhermitian** [comment] 2020-06-30 16:05
This is because we have moved away from simply pointing people to a github repo and actually putting the tutorials inside the qiskit docs. We actually do not need a start_here anymore, but it was left because there is no harm in keeping it around anyway. 

The legacy tutorials are either too long in runtime, do not work, or make api calls to the iqx. The latter was chosen not to be possible in the qiskit docs build process. So hosting them first requires modifications. This is why they are legacy.

**Comment by nonhermitian** [comment] 2020-07-09 09:27
Closing as not a bug.

**Closed by nonhermitian** 2020-07-09 09:27 UTC
Labels: bug
